### ISSUE TITLE
NPE Crashes

### ISSUE THREAD

**Issue by NielsPilgaard** [62832/AECapFix#1]
Heya! 
In Enigmatica 9 1.14.1 we've added AECapFix, and unfortunately several players crash because of it:

Crash 1: https://gist.github.com/Tepa00/234a5130f39979870f263cf657c3912f
Crash 2: https://gist.github.com/Aiidoneus/02452d1ef6fb158f835f58c24b7f78d3

In both cases removing AECapFix resolves the issue.

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/718

**Comment by MuteTiefling** [comment]
I had one as well, just placing a matter condenser: 
[crash-2023-10-10_12.35.55-client.txt](https://github.com/62832/AECapFix/files/12861715/crash-2023-10-10_12.35.55-client.txt)

**Comment by 62832** [comment]
Both of the initial crash logs provided seem to be caused by the Matter Condenser, so I'll have to look into that mixin and see where I went wrong.

EDIT: Alright, yeah, that was quick. Fix coming in a bit.
