### ISSUE TITLE
Powah reactor cannot accept items from RS exporter

### ISSUE THREAD

**Issue by Sandriell** [62832/AECapFix#2]
Added the mod and now my reactor will not accept items from a Refined Storage exporter, removed it and it works fine again.

Minecraft: 1.19.2
Forge: 43.2.21
AECapFix: 0.2.1
Powah: 4.0.11
Refined Storage: 1.11.6

**Comment by 62832** [comment]
Sorry about that, I messed up some logic for the reactor in particular.

AECF 0.4 should be released within the next 5 minutes to fix this.
